import type { INodeProperties } from 'n8n-workflow';
import { countryOptions, languageOptions } from '../../shared/locales';
import { simplifyProperty, zeroTraceOption } from '../../shared/output';

const showOnlyForSearchGoogle = {
	operation: ['searchGoogle'],
	resource: ['webSearch'],
};

export const webSearchSearchGoogleDescription: INodeProperties[] = [
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. best espresso machines',
		displayOptions: { show: showOnlyForSearchGoogle },
		description: 'The search query',
		routing: { send: { type: 'body', property: 'query' } },
	},
	simplifyProperty(showOnlyForSearchGoogle),
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: showOnlyForSearchGoogle },
		options: [
			{
				displayName: 'Country',
				name: 'gl',
				type: 'options',
				options: countryOptions,
				default: 'us',
				description: 'Country to search from',
				routing: { send: { type: 'body', property: 'gl' } },
			},
			{
				displayName: 'Device',
				name: 'device',
				type: 'options',
				options: [
					{ name: 'Desktop', value: 'desktop' },
					{ name: 'Mobile', value: 'mobile' },
					{ name: 'Tablet', value: 'tablet' },
				],
				default: 'desktop',
				description: 'Device to search as',
				routing: { send: { type: 'body', property: 'device' } },
			},
			{
				displayName: 'Disable Spelling Correction',
				name: 'nfpr',
				type: 'boolean',
				default: false,
				description: 'Whether to search the exact query without Google auto-correcting it',
				routing: { send: { type: 'body', property: 'nfpr', value: '={{ $value ? 1 : 0 }}' } },
			},
			{
				displayName: 'Google Domain',
				name: 'googleDomain',
				type: 'string',
				default: 'google.com',
				placeholder: 'e.g. google.co.uk',
				description: 'The Google domain to search on',
				routing: { send: { type: 'body', property: 'google_domain' } },
			},
			{
				displayName: 'Language',
				name: 'hl',
				type: 'options',
				options: languageOptions,
				default: 'en-US',
				description: 'Interface language for the results page',
				routing: { send: { type: 'body', property: 'hl' } },
			},
			{
				displayName: 'Latitude',
				name: 'latitude',
				type: 'number',
				typeOptions: { minValue: -90, maxValue: 90, numberPrecision: 6 },
				default: 0,
				description:
					'Search from these coordinates. Requires Longitude. Cannot be combined with Location or UULE.',
				routing: { send: { type: 'body', property: 'coordinates.latitude' } },
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'e.g. Austin,Texas,United States',
				description:
					'A Google Ads geo-target canonical name. Cannot be combined with coordinates or UULE.',
				routing: { send: { type: 'body', property: 'location' } },
			},
			{
				displayName: 'Longitude',
				name: 'longitude',
				type: 'number',
				typeOptions: { minValue: -180, maxValue: 180, numberPrecision: 6 },
				default: 0,
				description: 'Search from these coordinates. Requires Latitude.',
				routing: { send: { type: 'body', property: 'coordinates.longitude' } },
			},
			{
				displayName: 'Radius (Meters)',
				name: 'radius',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 1000 },
				default: 100,
				description:
					'Bias results around the coordinates. Max 199 on desktop, 1,000 on mobile or tablet.',
				routing: { send: { type: 'body', property: 'radius' } },
			},
			{
				displayName: 'Restrict to Countries',
				name: 'cr',
				type: 'string',
				default: '',
				placeholder: 'e.g. countryUS|countryCA',
				description: 'Only return documents from these countries',
				routing: { send: { type: 'body', property: 'cr' } },
			},
			{
				displayName: 'Restrict to Languages',
				name: 'lr',
				type: 'string',
				default: '',
				placeholder: 'e.g. lang_fr|lang_de',
				description: 'Only return documents in these languages',
				routing: { send: { type: 'body', property: 'lr' } },
			},
			{
				displayName: 'Safe Search',
				name: 'safe',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Off', value: 'off' },
				],
				default: 'active',
				routing: { send: { type: 'body', property: 'safe' } },
			},
			{
				displayName: 'Search Tab',
				name: 'udm',
				type: 'options',
				options: [
					{ name: 'AI Mode', value: 50 },
					{ name: 'Books', value: 36 },
					{ name: 'Forums', value: 6 },
					{ name: 'Images', value: 2 },
					{ name: 'Local', value: 1 },
					{ name: 'News', value: 12 },
					{ name: 'Shopping', value: 28 },
					{ name: 'Videos', value: 7 },
					{ name: 'Web', value: 14 },
				],
				default: 14,
				description: 'Which Google results tab to search',
				routing: { send: { type: 'body', property: 'udm' } },
			},
			{
				displayName: 'Start Offset',
				name: 'start',
				type: 'number',
				typeOptions: { minValue: 0 },
				default: 0,
				description: 'Zero-based result offset, e.g. 10 for the second page',
				routing: { send: { type: 'body', property: 'start' } },
			},
			{
				displayName: 'Time and Sort Filters (TBS)',
				name: 'tbs',
				type: 'string',
				default: '',
				placeholder: 'e.g. qdr:w',
				description:
					'Google\'s native advanced filters, e.g. "qdr:d" for the past day or "cdr:1,cd_min:8/1/2026,cd_max:8/12/2026" for a date range',
				routing: { send: { type: 'body', property: 'tbs' } },
			},
			{
				displayName: 'UULE',
				name: 'uule',
				type: 'string',
				default: '',
				placeholder: 'e.g. w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM',
				description:
					'Raw Google-encoded location. Cannot be combined with Location or coordinates.',
				routing: { send: { type: 'body', property: 'uule' } },
			},
			zeroTraceOption,
		],
	},
];
