// Generated by scripts/generate-options.mjs from https://www.prismcrawl.com/openapi.json (spec version 1.0.0). Do not edit by hand.
import type { INodePropertyOptions } from 'n8n-workflow';

export const countryOptions: INodePropertyOptions[] = [
	{
		name: 'Afghanistan (AF)',
		value: 'af',
	},
	{
		name: 'Åland Islands (AX)',
		value: 'ax',
	},
	{
		name: 'Albania (AL)',
		value: 'al',
	},
	{
		name: 'Algeria (DZ)',
		value: 'dz',
	},
	{
		name: 'American Samoa (AS)',
		value: 'as',
	},
	{
		name: 'Andorra (AD)',
		value: 'ad',
	},
	{
		name: 'Angola (AO)',
		value: 'ao',
	},
	{
		name: 'Anguilla (AI)',
		value: 'ai',
	},
	{
		name: 'Antarctica (AQ)',
		value: 'aq',
	},
	{
		name: 'Antigua & Barbuda (AG)',
		value: 'ag',
	},
	{
		name: 'Argentina (AR)',
		value: 'ar',
	},
	{
		name: 'Armenia (AM)',
		value: 'am',
	},
	{
		name: 'Aruba (AW)',
		value: 'aw',
	},
	{
		name: 'Australia (AU)',
		value: 'au',
	},
	{
		name: 'Austria (AT)',
		value: 'at',
	},
	{
		name: 'Azerbaijan (AZ)',
		value: 'az',
	},
	{
		name: 'Bahamas (BS)',
		value: 'bs',
	},
	{
		name: 'Bahrain (BH)',
		value: 'bh',
	},
	{
		name: 'Bangladesh (BD)',
		value: 'bd',
	},
	{
		name: 'Barbados (BB)',
		value: 'bb',
	},
	{
		name: 'Belarus (BY)',
		value: 'by',
	},
	{
		name: 'Belgium (BE)',
		value: 'be',
	},
	{
		name: 'Belize (BZ)',
		value: 'bz',
	},
	{
		name: 'Benin (BJ)',
		value: 'bj',
	},
	{
		name: 'Bermuda (BM)',
		value: 'bm',
	},
	{
		name: 'Bhutan (BT)',
		value: 'bt',
	},
	{
		name: 'Bolivia (BO)',
		value: 'bo',
	},
	{
		name: 'Bosnia & Herzegovina (BA)',
		value: 'ba',
	},
	{
		name: 'Botswana (BW)',
		value: 'bw',
	},
	{
		name: 'Bouvet Island (BV)',
		value: 'bv',
	},
	{
		name: 'Brazil (BR)',
		value: 'br',
	},
	{
		name: 'British Indian Ocean Territory (IO)',
		value: 'io',
	},
	{
		name: 'British Virgin Islands (VG)',
		value: 'vg',
	},
	{
		name: 'Brunei (BN)',
		value: 'bn',
	},
	{
		name: 'Bulgaria (BG)',
		value: 'bg',
	},
	{
		name: 'Burkina Faso (BF)',
		value: 'bf',
	},
	{
		name: 'Burundi (BI)',
		value: 'bi',
	},
	{
		name: 'Cambodia (KH)',
		value: 'kh',
	},
	{
		name: 'Cameroon (CM)',
		value: 'cm',
	},
	{
		name: 'Canada (CA)',
		value: 'ca',
	},
	{
		name: 'Cape Verde (CV)',
		value: 'cv',
	},
	{
		name: 'Caribbean Netherlands (BQ)',
		value: 'bq',
	},
	{
		name: 'Cayman Islands (KY)',
		value: 'ky',
	},
	{
		name: 'Central African Republic (CF)',
		value: 'cf',
	},
	{
		name: 'Chad (TD)',
		value: 'td',
	},
	{
		name: 'Chile (CL)',
		value: 'cl',
	},
	{
		name: 'China (CN)',
		value: 'cn',
	},
	{
		name: 'Christmas Island (CX)',
		value: 'cx',
	},
	{
		name: 'Cocos (Keeling) Islands (CC)',
		value: 'cc',
	},
	{
		name: 'Colombia (CO)',
		value: 'co',
	},
	{
		name: 'Comoros (KM)',
		value: 'km',
	},
	{
		name: 'Congo - Brazzaville (CG)',
		value: 'cg',
	},
	{
		name: 'Congo - Kinshasa (CD)',
		value: 'cd',
	},
	{
		name: 'Cook Islands (CK)',
		value: 'ck',
	},
	{
		name: 'Costa Rica (CR)',
		value: 'cr',
	},
	{
		name: 'Côte d’Ivoire (CI)',
		value: 'ci',
	},
	{
		name: 'Croatia (HR)',
		value: 'hr',
	},
	{
		name: 'Cuba (CU)',
		value: 'cu',
	},
	{
		name: 'Curaçao (AN)',
		value: 'an',
	},
	{
		name: 'Curaçao (CW)',
		value: 'cw',
	},
	{
		name: 'Cyprus (CY)',
		value: 'cy',
	},
	{
		name: 'Czechia (CZ)',
		value: 'cz',
	},
	{
		name: 'Denmark (DK)',
		value: 'dk',
	},
	{
		name: 'Djibouti (DJ)',
		value: 'dj',
	},
	{
		name: 'Dominica (DM)',
		value: 'dm',
	},
	{
		name: 'Dominican Republic (DO)',
		value: 'do',
	},
	{
		name: 'Ecuador (EC)',
		value: 'ec',
	},
	{
		name: 'Egypt (EG)',
		value: 'eg',
	},
	{
		name: 'El Salvador (SV)',
		value: 'sv',
	},
	{
		name: 'Equatorial Guinea (GQ)',
		value: 'gq',
	},
	{
		name: 'Eritrea (ER)',
		value: 'er',
	},
	{
		name: 'Estonia (EE)',
		value: 'ee',
	},
	{
		name: 'Eswatini (SZ)',
		value: 'sz',
	},
	{
		name: 'Ethiopia (ET)',
		value: 'et',
	},
	{
		name: 'Falkland Islands (FK)',
		value: 'fk',
	},
	{
		name: 'Faroe Islands (FO)',
		value: 'fo',
	},
	{
		name: 'Fiji (FJ)',
		value: 'fj',
	},
	{
		name: 'Finland (FI)',
		value: 'fi',
	},
	{
		name: 'France (FR)',
		value: 'fr',
	},
	{
		name: 'French Guiana (GF)',
		value: 'gf',
	},
	{
		name: 'French Polynesia (PF)',
		value: 'pf',
	},
	{
		name: 'French Southern Territories (TF)',
		value: 'tf',
	},
	{
		name: 'Gabon (GA)',
		value: 'ga',
	},
	{
		name: 'Gambia (GM)',
		value: 'gm',
	},
	{
		name: 'Georgia (GE)',
		value: 'ge',
	},
	{
		name: 'Germany (DE)',
		value: 'de',
	},
	{
		name: 'Ghana (GH)',
		value: 'gh',
	},
	{
		name: 'Gibraltar (GI)',
		value: 'gi',
	},
	{
		name: 'Greece (GR)',
		value: 'gr',
	},
	{
		name: 'Greenland (GL)',
		value: 'gl',
	},
	{
		name: 'Grenada (GD)',
		value: 'gd',
	},
	{
		name: 'Guadeloupe (GP)',
		value: 'gp',
	},
	{
		name: 'Guam (GU)',
		value: 'gu',
	},
	{
		name: 'Guatemala (GT)',
		value: 'gt',
	},
	{
		name: 'Guernsey (GG)',
		value: 'gg',
	},
	{
		name: 'Guinea (GN)',
		value: 'gn',
	},
	{
		name: 'Guinea-Bissau (GW)',
		value: 'gw',
	},
	{
		name: 'Guyana (GY)',
		value: 'gy',
	},
	{
		name: 'Haiti (HT)',
		value: 'ht',
	},
	{
		name: 'Heard & McDonald Islands (HM)',
		value: 'hm',
	},
	{
		name: 'Honduras (HN)',
		value: 'hn',
	},
	{
		name: 'Hong Kong SAR China (HK)',
		value: 'hk',
	},
	{
		name: 'Hungary (HU)',
		value: 'hu',
	},
	{
		name: 'Iceland (IS)',
		value: 'is',
	},
	{
		name: 'India (IN)',
		value: 'in',
	},
	{
		name: 'Indonesia (ID)',
		value: 'id',
	},
	{
		name: 'Iran (IR)',
		value: 'ir',
	},
	{
		name: 'Iraq (IQ)',
		value: 'iq',
	},
	{
		name: 'Ireland (IE)',
		value: 'ie',
	},
	{
		name: 'Isle of Man (IM)',
		value: 'im',
	},
	{
		name: 'Israel (IL)',
		value: 'il',
	},
	{
		name: 'Italy (IT)',
		value: 'it',
	},
	{
		name: 'Jamaica (JM)',
		value: 'jm',
	},
	{
		name: 'Japan (JP)',
		value: 'jp',
	},
	{
		name: 'Jersey (JE)',
		value: 'je',
	},
	{
		name: 'Jordan (JO)',
		value: 'jo',
	},
	{
		name: 'Kazakhstan (KZ)',
		value: 'kz',
	},
	{
		name: 'Kenya (KE)',
		value: 'ke',
	},
	{
		name: 'Kiribati (KI)',
		value: 'ki',
	},
	{
		name: 'Kuwait (KW)',
		value: 'kw',
	},
	{
		name: 'Kyrgyzstan (KG)',
		value: 'kg',
	},
	{
		name: 'Laos (LA)',
		value: 'la',
	},
	{
		name: 'Latvia (LV)',
		value: 'lv',
	},
	{
		name: 'Lebanon (LB)',
		value: 'lb',
	},
	{
		name: 'Lesotho (LS)',
		value: 'ls',
	},
	{
		name: 'Liberia (LR)',
		value: 'lr',
	},
	{
		name: 'Libya (LY)',
		value: 'ly',
	},
	{
		name: 'Liechtenstein (LI)',
		value: 'li',
	},
	{
		name: 'Lithuania (LT)',
		value: 'lt',
	},
	{
		name: 'Luxembourg (LU)',
		value: 'lu',
	},
	{
		name: 'Macao SAR China (MO)',
		value: 'mo',
	},
	{
		name: 'Madagascar (MG)',
		value: 'mg',
	},
	{
		name: 'Malawi (MW)',
		value: 'mw',
	},
	{
		name: 'Malaysia (MY)',
		value: 'my',
	},
	{
		name: 'Maldives (MV)',
		value: 'mv',
	},
	{
		name: 'Mali (ML)',
		value: 'ml',
	},
	{
		name: 'Malta (MT)',
		value: 'mt',
	},
	{
		name: 'Marshall Islands (MH)',
		value: 'mh',
	},
	{
		name: 'Martinique (MQ)',
		value: 'mq',
	},
	{
		name: 'Mauritania (MR)',
		value: 'mr',
	},
	{
		name: 'Mauritius (MU)',
		value: 'mu',
	},
	{
		name: 'Mayotte (YT)',
		value: 'yt',
	},
	{
		name: 'Mexico (MX)',
		value: 'mx',
	},
	{
		name: 'Micronesia (FM)',
		value: 'fm',
	},
	{
		name: 'Moldova (MD)',
		value: 'md',
	},
	{
		name: 'Monaco (MC)',
		value: 'mc',
	},
	{
		name: 'Mongolia (MN)',
		value: 'mn',
	},
	{
		name: 'Montenegro (ME)',
		value: 'me',
	},
	{
		name: 'Montserrat (MS)',
		value: 'ms',
	},
	{
		name: 'Morocco (MA)',
		value: 'ma',
	},
	{
		name: 'Mozambique (MZ)',
		value: 'mz',
	},
	{
		name: 'Myanmar (Burma) (MM)',
		value: 'mm',
	},
	{
		name: 'Namibia (NA)',
		value: 'na',
	},
	{
		name: 'Nauru (NR)',
		value: 'nr',
	},
	{
		name: 'Nepal (NP)',
		value: 'np',
	},
	{
		name: 'Netherlands (NL)',
		value: 'nl',
	},
	{
		name: 'New Caledonia (NC)',
		value: 'nc',
	},
	{
		name: 'New Zealand (NZ)',
		value: 'nz',
	},
	{
		name: 'Nicaragua (NI)',
		value: 'ni',
	},
	{
		name: 'Niger (NE)',
		value: 'ne',
	},
	{
		name: 'Nigeria (NG)',
		value: 'ng',
	},
	{
		name: 'Niue (NU)',
		value: 'nu',
	},
	{
		name: 'Norfolk Island (NF)',
		value: 'nf',
	},
	{
		name: 'North Korea (KP)',
		value: 'kp',
	},
	{
		name: 'North Macedonia (MK)',
		value: 'mk',
	},
	{
		name: 'Northern Mariana Islands (MP)',
		value: 'mp',
	},
	{
		name: 'Norway (NO)',
		value: 'no',
	},
	{
		name: 'Oman (OM)',
		value: 'om',
	},
	{
		name: 'Pakistan (PK)',
		value: 'pk',
	},
	{
		name: 'Palau (PW)',
		value: 'pw',
	},
	{
		name: 'Palestinian Territories (PS)',
		value: 'ps',
	},
	{
		name: 'Panama (PA)',
		value: 'pa',
	},
	{
		name: 'Papua New Guinea (PG)',
		value: 'pg',
	},
	{
		name: 'Paraguay (PY)',
		value: 'py',
	},
	{
		name: 'Peru (PE)',
		value: 'pe',
	},
	{
		name: 'Philippines (PH)',
		value: 'ph',
	},
	{
		name: 'Pitcairn Islands (PN)',
		value: 'pn',
	},
	{
		name: 'Poland (PL)',
		value: 'pl',
	},
	{
		name: 'Portugal (PT)',
		value: 'pt',
	},
	{
		name: 'Puerto Rico (PR)',
		value: 'pr',
	},
	{
		name: 'Qatar (QA)',
		value: 'qa',
	},
	{
		name: 'Réunion (RE)',
		value: 're',
	},
	{
		name: 'Romania (RO)',
		value: 'ro',
	},
	{
		name: 'Russia (RU)',
		value: 'ru',
	},
	{
		name: 'Rwanda (RW)',
		value: 'rw',
	},
	{
		name: 'Samoa (WS)',
		value: 'ws',
	},
	{
		name: 'San Marino (SM)',
		value: 'sm',
	},
	{
		name: 'São Tomé & Príncipe (ST)',
		value: 'st',
	},
	{
		name: 'Saudi Arabia (SA)',
		value: 'sa',
	},
	{
		name: 'Senegal (SN)',
		value: 'sn',
	},
	{
		name: 'Serbia (CS)',
		value: 'cs',
	},
	{
		name: 'Serbia (RS)',
		value: 'rs',
	},
	{
		name: 'Seychelles (SC)',
		value: 'sc',
	},
	{
		name: 'Sierra Leone (SL)',
		value: 'sl',
	},
	{
		name: 'Singapore (SG)',
		value: 'sg',
	},
	{
		name: 'Sint Maarten (SX)',
		value: 'sx',
	},
	{
		name: 'Slovakia (SK)',
		value: 'sk',
	},
	{
		name: 'Slovenia (SI)',
		value: 'si',
	},
	{
		name: 'Solomon Islands (SB)',
		value: 'sb',
	},
	{
		name: 'Somalia (SO)',
		value: 'so',
	},
	{
		name: 'South Africa (ZA)',
		value: 'za',
	},
	{
		name: 'South Georgia & South Sandwich Islands (GS)',
		value: 'gs',
	},
	{
		name: 'South Korea (KR)',
		value: 'kr',
	},
	{
		name: 'South Sudan (SS)',
		value: 'ss',
	},
	{
		name: 'Spain (ES)',
		value: 'es',
	},
	{
		name: 'Sri Lanka (LK)',
		value: 'lk',
	},
	{
		name: 'St. Barthélemy (BL)',
		value: 'bl',
	},
	{
		name: 'St. Helena (SH)',
		value: 'sh',
	},
	{
		name: 'St. Kitts & Nevis (KN)',
		value: 'kn',
	},
	{
		name: 'St. Lucia (LC)',
		value: 'lc',
	},
	{
		name: 'St. Martin (MF)',
		value: 'mf',
	},
	{
		name: 'St. Pierre & Miquelon (PM)',
		value: 'pm',
	},
	{
		name: 'St. Vincent & Grenadines (VC)',
		value: 'vc',
	},
	{
		name: 'Sudan (SD)',
		value: 'sd',
	},
	{
		name: 'Suriname (SR)',
		value: 'sr',
	},
	{
		name: 'Svalbard & Jan Mayen (SJ)',
		value: 'sj',
	},
	{
		name: 'Sweden (SE)',
		value: 'se',
	},
	{
		name: 'Switzerland (CH)',
		value: 'ch',
	},
	{
		name: 'Syria (SY)',
		value: 'sy',
	},
	{
		name: 'Taiwan (TW)',
		value: 'tw',
	},
	{
		name: 'Tajikistan (TJ)',
		value: 'tj',
	},
	{
		name: 'Tanzania (TZ)',
		value: 'tz',
	},
	{
		name: 'Thailand (TH)',
		value: 'th',
	},
	{
		name: 'Timor-Leste (TL)',
		value: 'tl',
	},
	{
		name: 'Togo (TG)',
		value: 'tg',
	},
	{
		name: 'Tokelau (TK)',
		value: 'tk',
	},
	{
		name: 'Tonga (TO)',
		value: 'to',
	},
	{
		name: 'Trinidad & Tobago (TT)',
		value: 'tt',
	},
	{
		name: 'Tunisia (TN)',
		value: 'tn',
	},
	{
		name: 'Türkiye (TR)',
		value: 'tr',
	},
	{
		name: 'Turkmenistan (TM)',
		value: 'tm',
	},
	{
		name: 'Turks & Caicos Islands (TC)',
		value: 'tc',
	},
	{
		name: 'Tuvalu (TV)',
		value: 'tv',
	},
	{
		name: 'U.S. Outlying Islands (UM)',
		value: 'um',
	},
	{
		name: 'U.S. Virgin Islands (VI)',
		value: 'vi',
	},
	{
		name: 'Uganda (UG)',
		value: 'ug',
	},
	{
		name: 'Ukraine (UA)',
		value: 'ua',
	},
	{
		name: 'United Arab Emirates (AE)',
		value: 'ae',
	},
	{
		name: 'United Kingdom (GB)',
		value: 'gb',
	},
	{
		name: 'United Kingdom (UK)',
		value: 'uk',
	},
	{
		name: 'United States (US)',
		value: 'us',
	},
	{
		name: 'Uruguay (UY)',
		value: 'uy',
	},
	{
		name: 'Uzbekistan (UZ)',
		value: 'uz',
	},
	{
		name: 'Vanuatu (VU)',
		value: 'vu',
	},
	{
		name: 'Vatican City (VA)',
		value: 'va',
	},
	{
		name: 'Venezuela (VE)',
		value: 've',
	},
	{
		name: 'Vietnam (VN)',
		value: 'vn',
	},
	{
		name: 'Wallis & Futuna (WF)',
		value: 'wf',
	},
	{
		name: 'Western Sahara (EH)',
		value: 'eh',
	},
	{
		name: 'Yemen (YE)',
		value: 'ye',
	},
	{
		name: 'Zambia (ZM)',
		value: 'zm',
	},
	{
		name: 'Zimbabwe (ZW)',
		value: 'zw',
	},
];

export const languageOptions: INodePropertyOptions[] = [
	{
		name: 'Afrikaans',
		value: 'af',
	},
	{
		name: 'Albanian',
		value: 'sq',
	},
	{
		name: 'American English',
		value: 'en-US',
	},
	{
		name: 'Amharic',
		value: 'am',
	},
	{
		name: 'Arabic',
		value: 'ar',
	},
	{
		name: 'Armenian',
		value: 'hy',
	},
	{
		name: 'Azerbaijani',
		value: 'az',
	},
	{
		name: 'Bangla',
		value: 'bn',
	},
	{
		name: 'Brazilian Portuguese',
		value: 'pt-BR',
	},
	{
		name: 'British English',
		value: 'en-GB',
	},
	{
		name: 'Bulgarian',
		value: 'bg',
	},
	{
		name: 'Burmese',
		value: 'my',
	},
	{
		name: 'Canadian French',
		value: 'fr-CA',
	},
	{
		name: 'Catalan',
		value: 'ca',
	},
	{
		name: 'Chinese (China)',
		value: 'zh-CN',
	},
	{
		name: 'Chinese (Taiwan)',
		value: 'zh-TW',
	},
	{
		name: 'Croatian',
		value: 'hr',
	},
	{
		name: 'Czech',
		value: 'cs',
	},
	{
		name: 'Danish',
		value: 'da',
	},
	{
		name: 'Dutch',
		value: 'nl',
	},
	{
		name: 'English',
		value: 'en',
	},
	{
		name: 'Estonian',
		value: 'et',
	},
	{
		name: 'European Portuguese',
		value: 'pt-PT',
	},
	{
		name: 'Filipino',
		value: 'fil',
	},
	{
		name: 'Finnish',
		value: 'fi',
	},
	{
		name: 'French',
		value: 'fr',
	},
	{
		name: 'Georgian',
		value: 'ka',
	},
	{
		name: 'German',
		value: 'de',
	},
	{
		name: 'Greek',
		value: 'el',
	},
	{
		name: 'Gujarati',
		value: 'gu',
	},
	{
		name: 'Hebrew (HE)',
		value: 'he',
	},
	{
		name: 'Hebrew (IW)',
		value: 'iw',
	},
	{
		name: 'Hindi',
		value: 'hi',
	},
	{
		name: 'Hungarian',
		value: 'hu',
	},
	{
		name: 'Icelandic',
		value: 'is',
	},
	{
		name: 'Indonesian',
		value: 'id',
	},
	{
		name: 'Italian',
		value: 'it',
	},
	{
		name: 'Japanese',
		value: 'ja',
	},
	{
		name: 'Kannada',
		value: 'kn',
	},
	{
		name: 'Kazakh',
		value: 'kk',
	},
	{
		name: 'Khmer',
		value: 'km',
	},
	{
		name: 'Korean',
		value: 'ko',
	},
	{
		name: 'Kyrgyz',
		value: 'ky',
	},
	{
		name: 'Lao',
		value: 'lo',
	},
	{
		name: 'Latin American Spanish',
		value: 'es-419',
	},
	{
		name: 'Latvian',
		value: 'lv',
	},
	{
		name: 'Lithuanian',
		value: 'lt',
	},
	{
		name: 'Macedonian',
		value: 'mk',
	},
	{
		name: 'Malay',
		value: 'ms',
	},
	{
		name: 'Malayalam',
		value: 'ml',
	},
	{
		name: 'Marathi',
		value: 'mr',
	},
	{
		name: 'Mongolian',
		value: 'mn',
	},
	{
		name: 'Nepali',
		value: 'ne',
	},
	{
		name: 'Norwegian',
		value: 'no',
	},
	{
		name: 'Persian',
		value: 'fa',
	},
	{
		name: 'Polish',
		value: 'pl',
	},
	{
		name: 'Punjabi',
		value: 'pa',
	},
	{
		name: 'Romanian',
		value: 'ro',
	},
	{
		name: 'Russian',
		value: 'ru',
	},
	{
		name: 'Serbian',
		value: 'sr',
	},
	{
		name: 'Serbian (Latin)',
		value: 'sr-Latn',
	},
	{
		name: 'Sinhala',
		value: 'si',
	},
	{
		name: 'Slovak',
		value: 'sk',
	},
	{
		name: 'Slovenian',
		value: 'sl',
	},
	{
		name: 'Spanish',
		value: 'es',
	},
	{
		name: 'Swahili',
		value: 'sw',
	},
	{
		name: 'Swedish',
		value: 'sv',
	},
	{
		name: 'Tamil',
		value: 'ta',
	},
	{
		name: 'Telugu',
		value: 'te',
	},
	{
		name: 'Thai',
		value: 'th',
	},
	{
		name: 'Turkish',
		value: 'tr',
	},
	{
		name: 'Ukrainian',
		value: 'uk',
	},
	{
		name: 'Urdu',
		value: 'ur',
	},
	{
		name: 'Uzbek',
		value: 'uz',
	},
	{
		name: 'Vietnamese',
		value: 'vi',
	},
	{
		name: 'Welsh',
		value: 'cy',
	},
];
