// Regenerates nodes/Prismcrawl/shared/locales.ts from the live PrismCrawl OpenAPI spec.
// Usage: node scripts/generate-options.mjs [path-or-url-to-openapi.json]
import { readFile, writeFile } from 'node:fs/promises';

const source = process.argv[2] ?? 'https://www.prismcrawl.com/openapi.json';
const spec = JSON.parse(
	source.startsWith('http') ? await (await fetch(source)).text() : await readFile(source, 'utf8'),
);
const google = spec.components.schemas.GoogleSearchRequest.properties;

const regionNames = new Intl.DisplayNames(['en'], { type: 'region' });
const languageNames = new Intl.DisplayNames(['en'], { type: 'language' });

const label = (names, code) => {
	try {
		const name = names.of(code);
		return name && name.toLowerCase() !== code.toLowerCase() ? `${name} (${code})` : code;
	} catch {
		return code;
	}
};

const toOptions = (codes, getName) =>
	codes
		.filter((code) => code !== null)
		.map((code) => ({ name: getName(code), value: code }))
		.sort((a, b) => a.name.localeCompare(b.name));

const countries = toOptions(google.gl.enum, (code) => label(regionNames, code.toUpperCase()));
// Show plain language names (n8n lint requires title case); keep the code only to tell duplicates apart.
const languageName = (code) => {
	try {
		return languageNames.of(code) ?? code;
	} catch {
		return code;
	}
};
const languageNameCounts = Object.groupBy(google.hl.enum.filter(Boolean), languageName);
const languages = toOptions(google.hl.enum, (code) =>
	languageNameCounts[languageName(code)].length > 1
		? `${languageName(code)} (${code.toUpperCase()})`
		: languageName(code),
);

const render = (name, options) =>
	`export const ${name}: INodePropertyOptions[] = ${JSON.stringify(options, null, '\t')};\n`;

const output = `// Generated by scripts/generate-options.mjs from ${source} (spec version ${spec.info.version}). Do not edit by hand.
import type { INodePropertyOptions } from 'n8n-workflow';

${render('countryOptions', countries)}
${render('languageOptions', languages)}
`;

await writeFile(new URL('../nodes/Prismcrawl/shared/locales.ts', import.meta.url), output);
console.log(`Wrote ${countries.length} countries and ${languages.length} languages`);
